modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="jujutsu_neon"
version="1.10.0"
displayName="Jujutsu Neon ACTION VFX"
authors="Kira / SQUAD"
description='''Combat mod with charge skills, HUD, cursed energy, custom VFX and audio.'''

[[dependencies.jujutsu_neon]]
modId="forge"
mandatory=true
versionRange="[47.4.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.jujutsu_neon]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
